### PR TITLE
Allow booleans to be 'locked' (disabled but text not greyed)

### PR DESCRIPTION
**Pull request by JohnThomson**
This change is [Reviewable](https://reviewable.io/reviews/sillsdev/config-r/22)

### CODE REVIEW

**Review by andrew-polk — CHANGES_REQUESTED** [review]
> Reviewed 2 of 2 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/config-r/22)* status: all files reviewed, 1 unresolved discussion (waiting on @JohnThomson)

___
*[`lib/ContentPane.tsx` line 899 at r1](https://reviewable.io/reviews/sillsdev/config-r/22#-Nv3BGvi1005w1SmXOGi:-Nv3BGvi1005w1SmXOGj:b-v93tp3) ([raw file](https://github.com/sillsdev/config-r/blob/fd7762fd4846ab02ff2e8a5e0197971b9d569ba1/lib/ContentPane.tsx#L899)):*
> ```XML
>       control={control}
>       {...props}
>       disabled = {props.disabled && !props.locked}
> ```

If I'm understanding this, it means that if we set it to disabled and locked, it won't be disabled. That seems wrong.

**Review by JohnThomson — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/sillsdev/config-r/22)* status: all files reviewed, 1 unresolved discussion (waiting on @andrew-polk)

___
*[`lib/ContentPane.tsx` line 899 at r1](https://reviewable.io/reviews/sillsdev/config-r/22#-Nv3BGvi1005w1SmXOGi:-Nv3DIxoCX6HwlZ23YN3:bhz2atc) ([raw file](https://github.com/sillsdev/config-r/blob/fd1c9e559cb0898eb41ca63d9d4eee5f13e7aafc/lib/ContentPane.tsx#L899)):*
<details><summary><i>Previously, andrew-polk wrote…</i></summary><blockquote>

If I'm understanding this, it means that if we set it to disabled and locked, it won't be disabled. That seems wrong.
</blockquote></details>

I added a comment to explain.

**Comment by andrew-polk** [comment]
*[`lib/ContentPane.tsx` line 899 at r1](https://reviewable.io/reviews/sillsdev/config-r/22#-Nv3BGvi1005w1SmXOGi:-Nv3Ep4754rOInvITQqg:boux81p) ([raw file](https://github.com/sillsdev/config-r/blob/fd1c9e559cb0898eb41ca63d9d4eee5f13e7aafc/lib/ContentPane.tsx#L899)):*
<details><summary><i>Previously, JohnThomson (John Thomson) wrote…</i></summary><blockquote>

I added a comment to explain.
</blockquote></details>

It isn't showing up yet

**Review by andrew-polk — APPROVED** [review]
> Reviewed 1 of 1 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/sillsdev/config-r/22)* status: <span>:shipit:</span> complete! all files reviewed, all discussions resolved (waiting on @JohnThomson)

**Pull request merged**
